### ISSUE TITLE
Example for `files` input is invalid?

### ISSUE THREAD

**Issue by DavidAnson** [tbroadley/spellchecker-cli-action#7]
Recommended:
https://github.com/tbroadley/spellchecker-cli-action/blob/383b668a163d37a6ab488f323b1b3be43f276af0/README.md?plain=1#L47-L49

Implemented:
https://github.com/DavidAnson/markdownlint/actions/runs/2865219053/workflow

Error:
```
Invalid workflow file
The workflow is not valid. .github/workflows/spellcheck.yml (Line: 18, Col: 9): A sequence was not expected
```

What works:
https://github.com/DavidAnson/markdownlint/blob/faa61ffdb4ce2c9fae412daf692fdfebf08e380b/.github/workflows/spellcheck.yml#L17

I'm not a YAML expert, nor a GitHub Actions expert, but I think inputs must always be a string and the syntax shown in README produces a list?

**Comment by tbroadley** [comment]
Good catch, thank you! I've pushed a commit to fix the example. Sorry for the confusion.
